### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by tq-gerberp** [seebe/rzg_stuff#4]
Hello,

we are using your repo to build more recent Qt versions for our RZ/G2 based modules. Works great so far, just some minor adjustments were made to fullfil our specific needs. We'd like to provide our customers a patched version of this repo via Github. Would you mind adding a license to your repo that allows anyone to modify the repo and publish the changes?

Regards,
Paul Gerber,
TQ-Systems GmbH.

**Comment by seebe** [comment]
MIT license file added.

:)

**Comment by tq-gerberp** [comment]
That was quick, many thanks!
